-- AlterTable
ALTER TABLE "JobOffer" ADD COLUMN     "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UserFilters" ADD COLUMN     "expiredAfterDays" INTEGER NOT NULL DEFAULT 14;
